CREATE TABLE IF NOT EXISTS "Users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fullname" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(255) NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"role" VARCHAR(255) NOT NULL,
	"create_at" DATE,
	"update_at" DATE,
	"is_verified" BOOLEAN,
	"verified_at" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Customer" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"group" VARCHAR(255),
	"is_membership" BOOLEAN,
	"membership_no" VARCHAR(255),
	"pic_name" VARCHAR(255),
	"pic_contact" VARCHAR(255),
	"province" VARCHAR(255),
	"city" VARCHAR(255),
	"village" VARCHAR(255),
	"address" TEXT,
	"zip_code" VARCHAR(255),
	"occupation" VARCHAR(255),
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "Admin" (
	"user_id" INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"position" VARCHAR(255),
	"unit_lab" VARCHAR(255),
	"employee_no" VARCHAR(255),
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "Submission" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"no_registration" VARCHAR(255),
	"no_epi" VARCHAR(255),
	"no_ticket" VARCHAR(255) NOT NULL,
	"type_service" VARCHAR(255) NOT NULL,
	"purpose_of_test" TEXT NOT NULL,
	"date_of_send" DATE,
	"date_of_receive" DATE,
	"sample_taker" VARCHAR(255),
	"id_isikhnas" VARCHAR(255),
	"diagnosis_required" BOOLEAN,
	"agenda_no" VARCHAR(255),
	"cust_letter_no" VARCHAR(255),
	"courier_name" VARCHAR(255),
	"courier_contact" VARCHAR(255),
	"notes" TEXT,
	"samples_count" BIGINT NOT NULL,
	"process_status" VARCHAR(255) NOT NULL,
	"attachment_doc" PATH,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Billing" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"submission_id" INTEGER NOT NULL,
	"ebilling_code" VARCHAR(255),
	"total_amount" DECIMAL,
	"payment_status" VARCHAR(255),
	"paid_at" TIME,
	"issued_at" TIME,
	"invoice_doc" PATH,
	"proof_payment" PATH,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Samples" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"submission_id" INTEGER NOT NULL,
	"sample_code_cust" VARCHAR(255) NOT NULL,
	"sample_type" VARCHAR(255) NOT NULL,
	"species" VARCHAR(255),
	"age" VARCHAR(255),
	"volume" VARCHAR(255),
	"condition" VARCHAR(255),
	"location_smpl_taken" VARCHAR(255),
	"total_sample" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "TestRequest" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"samples_id" INTEGER NOT NULL,
	"test_service_id" INTEGER NOT NULL,
	"discount" DECIMAL,
	"price_at_moment" DECIMAL NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "TestService" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"test_name" VARCHAR(255) NOT NULL,
	"unit_lab" VARCHAR(255),
	"target" VARCHAR(255),
	"price" DECIMAL,
	"description" TEXT,
	"sample_reqmt" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "LhuDocuments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"submission_id" INTEGER NOT NULL,
	"no_lhu" VARCHAR(255) NOT NULL,
	"file_path" PATH,
	"date_of_pub" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Feedback" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"rating" INTEGER NOT NULL,
	"comments" TEXT,
	"create_at" TIME,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Complaint" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"subjects" VARCHAR(255) NOT NULL,
	"description" TEXT NOT NULL,
	"status" VARCHAR(255) NOT NULL,
	"admin_response" TEXT,
	"attachment_path" PATH,
	"create_at" DATE NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Customer"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Admin"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Customer"
ADD FOREIGN KEY("user_id") REFERENCES "Submission"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Submission"
ADD FOREIGN KEY("id") REFERENCES "Billing"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Submission"
ADD FOREIGN KEY("id") REFERENCES "LhuDocuments"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Admin"
ADD FOREIGN KEY("user_id") REFERENCES "TestService"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Admin"
ADD FOREIGN KEY("user_id") REFERENCES "Submission"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Submission"
ADD FOREIGN KEY("id") REFERENCES "Samples"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Samples"
ADD FOREIGN KEY("id") REFERENCES "TestRequest"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "TestRequest"
ADD FOREIGN KEY("id") REFERENCES "TestService"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;