package services

import (
	"bytes"
	"fmt"
	"time"

	"si-bvet/internal/dto"
	"si-bvet/internal/repositories"

	"github.com/xuri/excelize/v2"
)

func ExportSubmissionsExcel(
	req dto.ExportSubmissionRequest,
	exportedBy string,
) (*bytes.Buffer, error) {

	submissions, err := repositories.GetSubmissionsForExport(
		req.SubmissionIDs,
		req.ExportAll,
	)
	if err != nil {
		return nil, err
	}

	f := excelize.NewFile()

	// =========================
	// SHEET 1: METADATA
	// =========================
	metaSheet := "Metadata"
	f.SetSheetName("Sheet1", metaSheet)

	totalSamples := 0
	totalTests := 0

	for _, s := range submissions {
		totalSamples += len(s.Samples)
		for _, sample := range s.Samples {
			totalTests += len(sample.TestRequests)
		}
	}

	exportMode := "SELECTED"
	if req.ExportAll {
		exportMode = "ALL"
	}

	metadata := [][]interface{}{
		{"Generated At", time.Now().Format("2006-01-02 15:04:05")},
		{"Generated By", exportedBy},
		{"Export Mode", exportMode},
		{"Total Submissions", len(submissions)},
		{"Total Samples", totalSamples},
		{"Total Tests", totalTests},
	}

	for i, row := range metadata {
		f.SetCellValue(metaSheet, fmt.Sprintf("A%d", i+1), row[0])
		f.SetCellValue(metaSheet, fmt.Sprintf("B%d", i+1), row[1])
	}

	// =========================
	// SHEET 2: SUMMARY
	// =========================
	f.NewSheet("Summary")
	f.SetCellValue("Summary", "A1", "Submission ID")
	f.SetCellValue("Summary", "B1", "Customer")
	f.SetCellValue("Summary", "C1", "Email")
	f.SetCellValue("Summary", "D1", "Status")
	f.SetCellValue("Summary", "E1", "Samples Count")

	row := 2
	for _, s := range submissions {
		f.SetCellValue("Summary", fmt.Sprintf("A%d", row), s.ID)
		f.SetCellValue("Summary", fmt.Sprintf("B%d", row), s.User.FullName)
		f.SetCellValue("Summary", fmt.Sprintf("C%d", row), s.User.Email)
		f.SetCellValue("Summary", fmt.Sprintf("D%d", row), s.ProcessStatus)
		f.SetCellValue("Summary", fmt.Sprintf("E%d", row), len(s.Samples))
		row++
	}

	// =========================
	// SHEET 3: SAMPLES
	// =========================
	f.NewSheet("Samples")
	f.SetCellValue("Samples", "A1", "Submission ID")
	f.SetCellValue("Samples", "B1", "Sample Code")
	f.SetCellValue("Samples", "C1", "Sample Type")
	f.SetCellValue("Samples", "D1", "Species")

	row = 2
	for _, s := range submissions {
		for _, sample := range s.Samples {
			f.SetCellValue("Samples", fmt.Sprintf("A%d", row), s.ID)
			f.SetCellValue("Samples", fmt.Sprintf("B%d", row), sample.SampleCodeCust)
			f.SetCellValue("Samples", fmt.Sprintf("C%d", row), sample.SampleType)
			f.SetCellValue("Samples", fmt.Sprintf("D%d", row), sample.Species)
			row++
		}
	}

	// =========================
	// SHEET 4: TESTS
	// =========================
	f.NewSheet("Tests")
	f.SetCellValue("Tests", "A1", "Submission ID")
	f.SetCellValue("Tests", "B1", "Sample Code")
	f.SetCellValue("Tests", "C1", "Test Name")
	f.SetCellValue("Tests", "D1", "Price")

	row = 2
	for _, s := range submissions {
		for _, sample := range s.Samples {
			for _, test := range sample.TestRequests {
				f.SetCellValue("Tests", fmt.Sprintf("A%d", row), s.ID)
				f.SetCellValue("Tests", fmt.Sprintf("B%d", row), sample.SampleCodeCust)
				f.SetCellValue("Tests", fmt.Sprintf("C%d", row), test.TestService.TestName)
				f.SetCellValue("Tests", fmt.Sprintf("D%d", row), test.PriceAtMoment)
				row++
			}
		}
	}

	// =========================
	// SHEET 5: BILLING
	// =========================
	f.NewSheet("Billing")
	f.SetCellValue("Billing", "A1", "Submission ID")
	f.SetCellValue("Billing", "B1", "Billing Code")
	f.SetCellValue("Billing", "C1", "Amount")
	f.SetCellValue("Billing", "D1", "Payment Status")

	row = 2
	for _, s := range submissions {
		if s.Billing != nil {
			f.SetCellValue("Billing", fmt.Sprintf("A%d", row), s.ID)
			f.SetCellValue("Billing", fmt.Sprintf("B%d", row), s.Billing.EBillingCode)
			f.SetCellValue("Billing", fmt.Sprintf("C%d", row), s.Billing.TotalAmount)
			f.SetCellValue("Billing", fmt.Sprintf("D%d", row), s.Billing.PaymentStatus)
			row++
		}
	}

	buf := new(bytes.Buffer)
	if err := f.Write(buf); err != nil {
		return nil, err
	}

	return buf, nil
}